### ISSUE TITLE
Verification of signed AuthnRequest using HTTP-REDIRECT Binding fails

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/pysaml2#633]
## Code Version
Tested on current master branch.

## Steps to Reproduce
Using [this basic](https://github.com/peppelinux/Ansible-Shibboleth-IDP-SP-Debian/blob/master/roles/shib2sp/templates/shibboleth2.xml) Shibboleth SP configuration I get SignatureError on Authn Request to a pysaml2 IdP, if this have `'want_authn_requests_signed': True` in its configuration.

## Temporary solution
Disable HTTP-REDIRECT in IdP configuration to get shibboleth SP working only with HTTP-POST binding.

**Comment by peppelinux** [comment]
I think that this Is the problem:
https://github.com/knaperek/djangosaml2/blob/a343d103dad2583d0162dcd3071cf612352bd842/djangosaml2/views.py#L194

**Comment by peppelinux** [comment]
Here a good explaination of the occourrence and nature of this design error:

https://github.com/IdentityPython/pysaml2/issues/713

**Comment by peppelinux** [comment]
I think that the presence of the signature in saml2 authrequest, in HTTP-REDIRECT, is caused by
`want_authn_requests_only_with_valid_cert`

**Comment by peppelinux** [comment]
That's 
want_authn_requests_only_with_valid_cert

Don't use this in a idp configuration of the SP doesn't used to put the cert in the authnrequest. Otherwise, if absent, the idp Will reject the request

**Comment by c00kiemon5ter** [comment]
This is now fixed by 2f756ba

**Comment by vkadam** [comment]
This issue is still reproducible. I have `want_authn_requests_signed = True`, using SaToSa, which when received authn request called `idp.parse_authn_request` method from [line #189](https://github.com/IdentityPython/SATOSA/blob/master/src/satosa/frontends/saml2.py#L189) (which goes to [Server class](https://github.com/IdentityPython/pysaml2/blob/master/src/saml2/server.py#L229)) with only SAMLRequest params, as there is no way to pass SigAlg or Signature values to parse_authn_request method.

I tried to change SaToSa code, and use `sigver.verify_redirect_signature` before calling parse_authn_request but no luck, as because on idp config we have `want_authn_requests_signed` it still fails at request.loads method because SigAlg and Signature not embedded with SAMLRequest (as it would be for POST binding).

IMHO fix should be at `request._loads` method, which should access SigAlg and Signature along with SAMLRequest, and in case of REDIRECT Binding if SigAlg and Signature is provided + must=true then verify signature else fallback to checking sign in SAMLRequest payload for POST Binding.

**Comment by vkadam** [comment]
I have made a [commit on fork](https://github.com/vkadam/pysaml2/commit/d1b61188191a932805b5ef0230de14d10ea852d8). I am not use to writing python code, so haven't added test cases yet. 
If code look correct to you will appreciate if you can accept this and put on master.
I will see if I can spent some time to write test and make official PR, if I must. But I won't quick, as will need time to setup python env to run tests.

**Comment by c00kiemon5ter** [comment]
Thanks @vkadam. You are right, this is the case now and it needs to be fixed.

**Comment by vkadam** [comment]
@c00kiemon5ter thanks for re-opening the issue. Please have a loot at code I posted [here](https://github.com/vkadam/pysaml2/commit/d1b61188191a932805b5ef0230de14d10ea852d8). It's been working for me as expected.

**Comment by peppelinux** [comment]
Fixed here
https://github.com/IdentityPython/pysaml2/releases/tag/v7.1.0
