### ISSUE TITLE
Generate the metadata file failed in simple example of a SAML2 service provider

### ISSUE THREAD

**Issue by oakmegaeddie** [IdentityPython/pysaml2#814]
## Code Version

branch: `master`
version: maybe `v7.0.1` since it is the latest version on master branch

## Expected Behavior

It should generate a metadata file as written in the document.
https://pysaml2.readthedocs.io/en/latest/examples/sp.html

## Current Behavior

When I run this `make_metadata.py sp_conf.py > sp.xml`, error occurs:

```bash
FileNotFoundError: [Errno 2] No such file or directory: '../idp2/idp.xml'
```

Traceback:

```bash
Traceback (most recent call last):
  File "/Users/eddiehsu/.pyenv/versions/pysaml2_venv/bin/make_metadata.py", line 4, in <module>
    __import__('pkg_resources').run_script('pysaml2==7.0.1', 'make_metadata.py')
  File "/Users/eddiehsu/.pyenv/versions/pysaml2_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/eddiehsu/.pyenv/versions/pysaml2_venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/Users/eddiehsu/.pyenv/versions/3.8.3/envs/pysaml2_venv/lib/python3.8/site-packages/pysaml2-7.0.1-py3.8.egg/EGG-INFO/scripts/make_metadata.py", line 56, in <module>
    cnf = Config().load_file(fil)
  File "/Users/eddiehsu/.pyenv/versions/pysaml2_venv/lib/python3.8/site-packages/pysaml2-7.0.1-py3.8.egg/saml2/config.py", line 366, in load_file
    return self.load(copy.deepcopy(mod.CONFIG))
  File "/Users/eddiehsu/.pyenv/versions/pysaml2_venv/lib/python3.8/site-packages/pysaml2-7.0.1-py3.8.egg/saml2/config.py", line 337, in load
    self.load_complex(cnf)
  File "/Users/eddiehsu/.pyenv/versions/pysaml2_venv/lib/python3.8/site-packages/pysaml2-7.0.1-py3.8.egg/saml2/config.py", line 271, in load_complex
    self.setattr("", "metadata", self.load_metadata(cnf["metadata"]))
  File "/Users/eddiehsu/.pyenv/versions/pysaml2_venv/lib/python3.8/site-packages/pysaml2-7.0.1-py3.8.egg/saml2/config.py", line 387, in load_metadata
    mds.imp(metadata_conf)
  File "/Users/eddiehsu/.pyenv/versions/pysaml2_venv/lib/python3.8/site-packages/pysaml2-7.0.1-py3.8.egg/saml2/mdstore.py", line 1090, in imp
    self.load(key, val)
  File "/Users/eddiehsu/.pyenv/versions/pysaml2_venv/lib/python3.8/site-packages/pysaml2-7.0.1-py3.8.egg/saml2/mdstore.py", line 1076, in load
    _md.load()
  File "/Users/eddiehsu/.pyenv/versions/pysaml2_venv/lib/python3.8/site-packages/pysaml2-7.0.1-py3.8.egg/saml2/mdstore.py", line 777, in load
    _txt = self.get_metadata_content()
  File "/Users/eddiehsu/.pyenv/versions/pysaml2_venv/lib/python3.8/site-packages/pysaml2-7.0.1-py3.8.egg/saml2/mdstore.py", line 773, in get_metadata_content
    with open(self.filename, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '../idp2/idp.xml'
```

## Possible Solution

I guess either the document should be corrected, or the `idp.xml` file should be added.
I searched in the repository, found some `idp.xml` files in `test` folder, but I don't know whether I can use them or not.

## Steps to Reproduce

Following the steps in https://pysaml2.readthedocs.io/en/latest/examples/sp.html

```python
cd [your path]/pysaml2/example/sp-wsgi
cp service_conf.py.example service_conf.py
cp sp_conf.py.example sp_conf.py
```

```python
cd [your path]/pysaml2/example/sp-wsgi
make_metadata.py sp_conf.py > sp.xml
```

**Comment by c00kiemon5ter** [comment]
This is an annoying issue of the examples. I need to look into this and resolve it.
See also, https://github.com/IdentityPython/pysaml2/issues/737#issuecomment-754939360

Notice, on the metadata snippet on the comment the attribute `validUntil`. Change it from `validUntil="2021-01-12T22:13:11Z"` to a future date, otherwise validation will fail.

**Comment by webmaxttor** [comment]
The problem is a "cross dependency" between SP and IDP configurations.  IDP references sp.xml and SP references the idp.xml.

Its simple to work around this.
- Comment out this line in idp_conf.py
#        "local": [full_path("../sp-wsgi/sp.xml")],
- generate the idp.xml
- generate the sp.xml
and remove the comment again...

One solution is ignore the exception, log the error, and generate the xml file anyway. So the user will be able to follow the doc
or just add the example xml file

**Comment by c00kiemon5ter** [comment]
closed by d88ad14 

I've added a metadata file for the example-IdP without a validUntil property, which should fix the issue.

**Comment by fmalina** [comment]
I still experienced this issue and @webmaxttor 's suggestion sorted it
